name 'puppet-samba'
version '0.1.0'
source 'https://github.com/jonmosco/puppet-samba.git'
author 'Jon Mosco'
license 'Apache 2.0'
summary 'Samba module for Puppet'
dependency 'ripienaar/concat', '>= 0.2.0'
dependency 'puppetlabs/stdlib', '>=3.2.0'
