HOSTS:
  centos-6-docker-x64:
    roles:
      - master
    platform: el-6-x86_64
    image: centos:centos6
    hypervisor: docker
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'yum install -y tar wget ntpdate rubygems ruby-augeas ruby-devel'
    docker_preserve_image: true
CONFIG:
  type: foss
